### ISSUE TITLE
Crash upon creating world

### ISSUE THREAD

**Issue by Rongmario** [LXGaming/Sledgehammer#1]
https://paste.dimdev.org/bakeramowe.mccrash

**Comment by LXGaming** [comment]
What modpack are you running? Looking at the code for Patchouli I can't see anything that would directly cause this issue.

**Comment by Rongmario** [comment]
Custom. As soon as I remove it I'm able to load it again..

**Comment by xElementzx** [comment]
May i suggest trying out PI
https://minecraft.curseforge.com/projects/project-intelligence as a replacement for Patchouli

**Comment by Rongmario** [comment]
@xElementzx Twilight Forest + Cuisine, which are in my pack, requires Patchouli.

**Comment by LXGaming** [comment]
@Rongmario Can you provided the latest.log and debug.log from your Client when the crash occurs.
