### ISSUE TITLE
Could you also fix this issue?

### ISSUE THREAD

**Issue by Spontini** [LXGaming/Sledgehammer#13]
Hello, as you can see this issue creates in 2019 but still had no fix for it, is it possible that you can fix it with Seldgehammer?

https://github.com/DarkPacks/SkyFactory-4/issues/1279

**Comment by LXGaming** [comment]
Please test the fix in [Sledgehammer v2.0.4-BETA](https://github.com/LXGaming/Sledgehammer/releases/tag/v2.0.4-BETA)

Make sure to set `item-duplication` under the `realfilingcabinet` to `true` in the config.

The issue appears to be realfilingcabinet modifying the ItemStack from the Forge ItemStackHandler, Forge JavaDocs clearly state to NOT modify the ItemStack.

From quickly testing it does appear to fix the issue however there is some weird desync in WAILA where the amount will keep increasing, opening the Transfer Node and then opening or closing the Filing Cabinet does force it to show the correct value.
