### ISSUE TITLE
Crash with CodeChickenLib

### ISSUE THREAD

**Issue by LukaPix** [LXGaming/Sledgehammer#14]
When enabling your mod in my Modpack it makes CodeChickenLib crash.
I am using Version 2.0.4 with Mixin 0.7
[debug.log](https://github.com/LXGaming/Sledgehammer/files/4783348/debug.log)

**Comment by LXGaming** [comment]
Disable `interact-events` in the config, Make sure all of the settings under the `sponge` category are set to `false`.

**Comment by LXGaming** [comment]
Comment or reopen if you're still having issues
