### ISSUE TITLE
Bewitchment Patches

### ISSUE THREAD

**Issue by mxnmnm** [LXGaming/Sledgehammer#15]
Would it be possible to make a blacklist for mobs that can't be tamed with the new friend potions/thyrsus? The main one that comes to mind is an ice and fire dragon. Another thing that should be fixed is the ability to take other people's pets. These would fit in perfectly with the kind of fixes this mod does.

**Comment by mxnmnm** [comment]
Also an option to disable the broom ritual would be really nice considering how buggy brooms are and how they aren't likely to get fixed.

**Comment by LXGaming** [comment]
https://github.com/LXGaming/Sledgehammer/releases/tag/v2.0.9
