### ISSUE TITLE
crash with ender io 5.2.60+

### ISSUE THREAD

**Issue by xemnes** [LXGaming/Sledgehammer#17]
reported this problem on the ender io github, they claim its because of sledgehammer so im reporting this here https://github.com/SleepyTrousers/EnderIO/issues/5458

**Comment by LXGaming** [comment]
Try setting `recipe-factory-stacktrace` to false in the config.

That Mixin may no longer be valid for newer EnderIO versions

**Comment by xemnes** [comment]
yup, that fixed it. thanks.

**Comment by xJon** [comment]
> That Mixin may no longer be valid for newer EnderIO versions

Would be useful to add this information in the config file for future reference :)
