### ISSUE TITLE
Thaumic Wonders Compat

### ISSUE THREAD

**Issue by mxnmnm** [LXGaming/Sledgehammer#18]
Thaumic Wonders lets the player change time and the weather so it would fit in very nicely with the other compats you have for mods that do similar things.

**Comment by LXGaming** [comment]
Pre-release available: https://github.com/LXGaming/Sledgehammer/releases/tag/v2.0.10-DEV

I've patched the Meteorb and Timewinder as from doing a quick search thoses were the only things I could find that made the calls to change the time / weather.

**Comment by mxnmnm** [comment]
Yay thanks!
