### ISSUE TITLE
1.12.2 Log spam with "Tried to mark PlayerChunkMapEntry as dirty while locked"

### ISSUE THREAD

**Issue by jarezzz** [LXGaming/Sledgehammer#19]
Not asking for actual solution but only for a config option to suppress any logs about "Tried to mark PlayerChunkMapEntry as dirty while locked". Tried commenting out those PrettyPrinters in PlayerChunkMapMixin.java in onEntryChanged() and onRemoveEntry() but failed at building the jar file, kinda tricky since it is not a conventional gradlew from mdk and I am not so profound in java.

Can we have it? Removed most of the worldgen mods but it is still happens. Pretty please!

**Comment by LXGaming** [comment]
You can disable the patch entirely by setting `player-chunk-map` to `false` in the config, however if you require the patch without the log messages I can look into it.

**Comment by jarezzz** [comment]
Oh, so it was that simple, guess I need to read more carefully, thanks for a quick answer!
