### ISSUE TITLE
Vaultopic fixable issue?

### ISSUE THREAD

**Issue by Rsslone** [LXGaming/Sledgehammer#25]
I've reported this to the dev of vaultopic. I was hoping sledge hammers fix would fix this, but is there anything you read from this gibberish?

https://github.com/wolforcept/Vaultopic/issues/13

**Comment by Rsslone** [comment]
Currently experimenting with placing it into the broken mods list for sponge for the netty handler. I'll comment any updates I find.

**Comment by Rsslone** [comment]
I managed to fix the issue, If someone else finds this thread, you need to do the following in your global sponge config.

I'll leave this ticket open in case there is something sledge hammer can do for this, otherwise close it as there is a manageable work around.

`    broken-mods {
        # A list of mod ids that have broken network handlers (they interact with the game from a Netty handler thread).
        # All network handlers from a forcibly scheduled to run on the main thread.
        # Note that this setting should be considered a last resort, and should only be used as a stopgap measure
        # while waiting for a mod to properly fix the issue.
        broken-network-handler-mods=["vaultopic"]
`
And
`
        # Enables experimental fixes for broken mods
        broken-mod=true
`

**Comment by LXGaming** [comment]
Fixed in [v1.12.2-2.0.13](https://github.com/LXGaming/Sledgehammer/releases/tag/v1.12.2-2.0.13)

**Comment by Rsslone** [comment]
You're a legend, thank you!
