### ISSUE TITLE
BiblioCraft Patch? 

### ISSUE THREAD

**Issue by Aiidoneus** [LXGaming/Sledgehammer#26]
Hello,
I am not sure this is doable but let me know if it is at all. 
Lately, we have been getting this on a lot of our 1.12.2 servers.
https://gist.github.com/Aiidoneus/6906eb7f3fa46fbd6ebc2cc2fc868c18
Now, there are a lot of issues regarding this. See 
https://github.com/Nuchaz/BiblioCraft/issues?q=is%3Aissue+is%3Aopen+getStackInSlot

Notable issue with an explanation to what is happening is this. https://github.com/McJtyMods/RFTools/issues/1886

Currently running BiblioCraft[v2.4.5][MC1.12.2].jar if that helps? I can provide any additional info if needed

**Comment by LXGaming** [comment]
Fixed in [v1.12.2-2.0.15](https://github.com/LXGaming/Sledgehammer/releases/tag/v1.12.2-2.0.15)

**Comment by Aiidoneus** [comment]
Thank you very much!
