### ISSUE TITLE
Phase error with PlayerChunkMap

### ISSUE THREAD

**Issue by Shybella** [LXGaming/Sledgehammer#3]
https://pastebin.com/raw/GBjB3bDg

Stoneblock2 + SF RB

**Comment by LXGaming** [comment]
This warning is apart of the `player-chunk-map` fix, It prevents a ConcurrentModificationException from occurring which would crash the entire server.

I suggest ether updating Sponge or try disabling the fix in Sledgehammer, if your server crashes then it's an issue with COFHWorld or Sponge.
