### ISSUE TITLE
Yabba Barrel Drops another Barrel When Picked Up with Chest Transporter

### ISSUE THREAD

**Issue by Aiidoneus** [LXGaming/Sledgehammer#30]
Hello,
I do not know if you take requests but I have a bug currently present on Stoneblock 2 modpack. I linked the issue to the chest transporter dev already. It would be really awesome if you could help fix it though. 

Reported here: https://github.com/cubex2/chesttransporter/issues/40

Basically all you need to do is pickup the yabba barrel or yabba anti-barrel with a chest transporter and it drops one in the world like you broke it. 

Let me know if you need any other info!

**Comment by LXGaming** [comment]
Fixed in [v1.12.2-2.0.17](https://github.com/LXGaming/Sledgehammer/releases/tag/v1.12.2-2.0.17)
