### ISSUE TITLE
Xinghui magic problem

### ISSUE THREAD

**Issue by 623667595** [LXGaming/Sledgehammer#33]
In my server, after players have learned most of the star abilities, they will drop the line with a high probability when transmitting other worlds

**Comment by LXGaming** [comment]
Could you please link the mod and provide any logs relating to the error.

**Comment by 623667595** [comment]
[2022-06-23-4.log](https://github.com/LXGaming/Sledgehammer/files/8963722/2022-06-23-4.log)
After upgrading the star capability, it will be transmitted to other worlds to drop the line. It seems that there is no error reported in the background. I send a crash log of my past, which contains my mod information

**Comment by LXGaming** [comment]
I don't know which mod you are referring to. Can you link the CurseForge page for the mod you are having issues with.

**Comment by 623667595** [comment]
https://github.com/HellFirePvP/AstralSorcery
This is the mod

**Comment by 623667595** [comment]
https://www.curseforge.com/minecraft/mc-mods/astral-sorcery
1.12.2mod author has stopped changing

**Comment by LXGaming** [comment]
Set `data-serializers` to `false` under the `astral-sorcery` category in the Sledgehammer Config. This patch isn't need when running [AstralSorcery-1.12.2-1.10.27](https://www.curseforge.com/minecraft/mc-mods/astral-sorcery/files/3044416) and having it enabled may be causing your issues.

**Comment by 623667595** [comment]
Without sledgehamme, this bug will also be triggered. I don't know what indicator overflowed or what bug. I don't think this bug can be fixed.

**Comment by LXGaming** [comment]
Make sure that config option is disabled and AstralSorcery is up-to-date on both client and server, There was an update to AstralSorcery which addressed disconnection issues.

**Comment by 623667595** [comment]
I don't know which setting to disable. Many computers are very confused

**Comment by 623667595** [comment]
I have changed the configuration according to what you said, but this problem still occurs

**Comment by LXGaming** [comment]
Unless you can obtain logs that contain an error relating to the disconnect issues there is not much I can do to help.

**Comment by 623667595** [comment]
I have already tested it. As long as there are more than 30 skill points, this will happen. I set a maximum of 100. Can I issue relevant patches?

**Comment by 623667595** [comment]
掉线会显示这个
![image](https://user-images.githubusercontent.com/88877796/175763017-d2274bd9-0229-40e8-8b05-aa6a29827e14.png)

**Comment by 623667595** [comment]
He will terminate the established connection, or the connection times out

**Comment by LXGaming** [comment]
Are you playing a modpack? Could you please link it

**Comment by 623667595** [comment]
已经花钱找人修复了，是1.12.2星辉魔法本身问题

**Comment by LXGaming** [comment]
What modpack are you playing so that I can attempt to reproduce this issue

**Comment by 623667595** [comment]
自制的整合包，实现原理就是点了很多星能力后【我设置的最高100星能力】传送到其他世界几率性掉线，特别是玩一段时间后，传送其他世界掉线概率很大。有多世界插件。据我所知都是1.12.2星辉魔法遗留的问题，作者已经停更了。我买的修复补丁，就完事了

**Comment by LXGaming** [comment]
![2022-07-09_17 15 33](https://user-images.githubusercontent.com/10443061/178092838-1d76fa08-ad3e-4e26-b085-8752e70175e7.png)
I gave myself every perk and haven't encountered any disconnection issues, unless you can reproduce this issue with just Astral Sorcery there isn't anything more I can do.
I suspect that this issue is ether caused by another mod or a combination of mods and that there is 
potentially too much data being transmitted when switching worlds that is just causing general networking issues.
