### ISSUE TITLE
Request: disable PneumaticCraft hacking

### ISSUE THREAD

**Issue by freopt** [LXGaming/Sledgehammer#35]
In PNC you can "hack" blocks and entities with the pneumatic helmet, and it currently can't be disabled. You can remove the recipes for the upgrades that allow it but they have other functions.

**Comment by LXGaming** [comment]
Which Minecraft version? I'm assuming 1.12.2

**Comment by LXGaming** [comment]
Assuming you wanted it patched in 1.12.2, Please test [v1.12.2-2.0.20](https://github.com/LXGaming/Sledgehammer/releases/tag/v1.12.2-2.0.20)

Make sure to set `disable-hacking` under the `pneumaticcraft` section to true in the config.

**Comment by freopt** [comment]
It works, tysm
