### ISSUE TITLE
Spongeforge & Cyclic Cyclic Automated User and Click Machine Auto Clicker

### ISSUE THREAD

**Issue by Aiidoneus** [LXGaming/Sledgehammer#36]
Hello,
This was reported a while ago to the SpongeForge team but nobody seems to have found what the issue is. Could be cool if you can look into this. I know this is a long shot but I am willing to test or help out in anyway on my side. 

https://github.com/SpongePowered/SpongeForge/issues/3205

This should have the relevant information I believe.

**Comment by LXGaming** [comment]
What blocks are you trying to automate clicks for? I tested fences and they worked fine.
