### ISSUE TITLE
[1.12.2] Sledgehammer deleting boats even when patch disabled.

### ISSUE THREAD

**Issue by Zilacon** [LXGaming/Sledgehammer#37]
SH Version: 1.12.2 #20
Server: CatServer 1.12.2
OS: Linux Lubuntu
Java: AdoptOpenJDK 8

Even with the boat purge and boat crash patches disabled in the config, boats are disappearing when placed. This is happening on several servers at the same time.

**Comment by LXGaming** [comment]
Can you please upload your debug.log

**Comment by Zilacon** [comment]
[debug.log](https://github.com/LXGaming/Sledgehammer/files/10077955/debug.log)

**Comment by LXGaming** [comment]
What modpack is this? I'll have to do some testing, Looking at the log you provided I don't see the `boat-purge` or `boat-crash` patches being enabled so the config is working correctly.

Does this work with Sledgehammer removed?
Could this be an OpenJ9 issue?

**Comment by Zilacon** [comment]
Theres no issues with boats without sledgehammer.
This is on the Hexxit Updated pack on curse.
It can also be replicated on The 1.12.2 Pack, Hexxit 2, RL Craft, and Tekxit Pi

**Comment by LXGaming** [comment]
I can't seem to be able to reproduce this issue, even with CatServer and OpenJ9, `boat-crash` is client side only and `boat-purge` only removes Biomes O' Plenty boats.

Are Vanilla, BOP and The Betweenlands Boats disappearing or is it just BOP?
Does this still happen with all Sledgehammer patches disabled?

**Comment by LXGaming** [comment]
Please test [v1.12.2-2.0.21](https://github.com/LXGaming/Sledgehammer/releases/tag/v1.12.2-2.0.21), Set `debug` to `true` in the `sledgehammer.conf`, It will log if the `boat-purge` patch is actually responsible.

Could you please ether zip your server and upload it somewhere or document the changes you've made to the modpack (the less changes the better) so I can reproduce the issue and investigate further.

**Comment by Zilacon** [comment]
Besides sledgehammer ive added:
Phosphor 0.2.9.2
EntityDesyncFix 1.0.2
MixinBooter 5.0
ReachFix 1.0.6
FoamFix 0.10.15
DupeFixProject 3.1.6
WorldEdit 6.1.10
EventHelper 2.8.1
Grimoire 3.2.8
LoliASM 5.6
FastLeafDecay v14
Performant 1.11
RandomPatches 1.22.1.10
NetherPortalFix 5.317
MixinCompar 0.8
FantasticLib
BetterFPS 1.4.8
AI Improvements 0.0.1b1
ChunkGenLimiter 1.1
SignalCatcher 1.1
HelpFixer 1.5.18
BedPatch 2.2
Suirge 2.0.79
AiReducer 0.1.3
RLTweaker 0.5.1
[AddedMods.zip](https://github.com/LXGaming/Sledgehammer/files/10083209/AddedMods.zip)

**Comment by LXGaming** [comment]
I've tried to replicate your server environment as closely as I can and I still cannot reproduce this issue, unless you can reproduce this issue with minimal changes made to the modpack there isn't much I can do to investigate, as it stands there are too many variables;
- you've added mods to the modpack
- you're running CatServer and not the latest version which means I can't easily download the build your using, also don't know if you have Bukkit/Spigot plugins installed
- you're running OpenJ9 1.8.0_302-internal and while I can find builds for `1.8.0_302` I cannot find a build which has `internal` which funnily enough is causing LoliASM to throw an error
- I don't know what configs you've altered

Are Vanilla, BOP and The Betweenlands Boats disappearing or is it just BOP?
Do the boats appear at all even for a split second?
Does this still happen with all Sledgehammer patches disabled?
Are you modifying / adding Sledgehammer to your client?
Have you tested [v1.12.2-2.0.21](https://github.com/LXGaming/Sledgehammer/releases/tag/v1.12.2-2.0.21)?
