### ISSUE TITLE
[Request]Fix serveral bugs in Tinkers' Evolution and Tinkers' Construct 2

### ISSUE THREAD

**Issue by ghost** [LXGaming/Sledgehammer#39]
1.https://github.com/phantamanta44/tinkers-evolution/issues/127

2.https://github.com/phantamanta44/tinkers-evolution/issues/114

3.If a tool has the Evolved modifier in Tinkers' Evolution,each item can make it increase a level (eg nether quartz for attack damage)after engraving.

4.https://github.com/SlimeKnights/TinkersConstruct/issues/3857

Maybe some of them can be fixed,I can help in any way I can.

**Comment by LXGaming** [comment]
I've fixed 2 & 4.

I'm having issues understanding how to reproduce 1 & 3, If you could provide step by step instructions for reproducing those issues then I'll be able to investigate them further.

**Comment by ghost** [comment]
Thank you.For 1 & 3,I'll make a step about how to reproduce the problem on weekend.

**Comment by ghost** [comment]
For 1
Things needed
![image](https://user-images.githubusercontent.com/103164772/233342505-ca936cd9-0dc2-4088-a5c9-971b66850e45.png)
1.
![image](https://user-images.githubusercontent.com/103164772/233342569-e83b36c1-39a6-4d5d-ad51-9787716494ee.png)
2.
![image](https://user-images.githubusercontent.com/103164772/233342627-f61b746f-d32a-4474-ae8a-4aa3c6c6c765.png)
Bug:
![image](https://user-images.githubusercontent.com/103164772/233342732-fb9b9b59-5b32-4a37-b5f8-39051de19031.png)
![image](https://user-images.githubusercontent.com/103164772/233342788-87e20a04-97c8-4757-8f45-edcfb55f1b7a.png)
Then you can add huge amount of attack damage(or something else)

**Comment by ghost** [comment]
@LXGaming 
I reproduced problem 3, and by then I forgot how problem 1 was reproduced, so I'll leave it for now, but I found a new problem that needs to be fixed:https://github.com/SlimeKnights/TinkersConstruct/issues/3997

**Comment by LXGaming** [comment]
I believe I've found and fixed the root cause of the Tool Forge Dupe, Tinkers isn't syncing the `toolName` to every other open container which causes the `renameTool` logic to fail which prevents the input slots from being cleared resulting in the duplication.

I've got a partial fix for 3 and that's to prevent the LevelAspect from going above the maximum level (Tinkers Construct has logic to prevent this but Tinkers Evolution seems to be working around it), each craft of the tool increases the Draconic Modifiers which is where the attack damage is coming from. I'm unsure how to correctly fix this.

@mczph How are the Draconic Modifiers normally upgraded? I assume they shouldn't be upgraded with each craft of the tool?

**Comment by ghost** [comment]
Yes,so it's why this is a bug.Nomally, you should put your tools into Draconic Evolution's Fusion Crafting core and add some items with a upgrade key to upgrade it for 3 levels at most.

**Comment by ghost** [comment]
I have also noticed that there is a pr:https://github.com/phantamanta44/tinkers-evolution/pull/109
Is is related to this bug?

**Comment by LXGaming** [comment]
> Yes,so it's why this is a bug.Nomally, you should put your tools into Draconic Evolution's Fusion Crafting core and add some items with a upgrade key to upgrade it for 3 levels at most.

Ah, I see


> I have also noticed that there is a pr:[phantamanta44/tinkers-evolution#109](https://github.com/phantamanta44/tinkers-evolution/pull/109)

That PR looks like it would stop the level going above 4 but it won't stop it from reaching 4 which is the issue.

**Comment by LXGaming** [comment]
3 should be fixed now.
If you patch it server side only there is a visual glitch on the client where the Tool Forge will indicate that the Draconic level will increase, it won't. You can install Sledgehammer on the client to fix the issue but as it's only visual it's not necessary.

**Comment by ghost** [comment]
Thank you.Since so many 1.12 mods authors stop updating,I maybe report more bugs in the future.

**Comment by LXGaming** [comment]
No problem, Thank you for help.

[v1.12.2-2.0.23](https://github.com/LXGaming/Sledgehammer/releases/tag/v1.12.2-2.0.23)
