### ISSUE TITLE
What means `Mixin apply failed RecipeFactoryMixin`?

### ISSUE THREAD

**Issue by Krutoy242** [LXGaming/Sledgehammer#42]
I recently installed and configured Sledgehammer for my modpack [E2E-E](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended).

After launching game i found this warning in `debug.log` file:

```less
[Client thread/WARN] [mixin]: Mixin apply failed mixins.sledgehammer.enderio.json:base.config.recipes.RecipeFactoryMixin -> crazypants.enderio.base.config.recipes.RecipeFactory: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on onError could not find any targets matching 'copyCore_dontMakeShittyCoreModsPlease' in crazypants.enderio.base.config.recipes.RecipeFactory. Using refmap mixins.sledgehammer.refmap.json [ -> handler$zep000$onError(Lnet/minecraft/util/ResourceLocation;Ljava/io/File;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/io/IOException;)V -> Parse]
```

What does this warning means? Is that means `recipe-factory-stacktrace=true` config option not working? If so, how i can find mod that interfere Sledgehammer to work properly?

[debug.log](https://github.com/LXGaming/Sledgehammer/files/11451948/debug.log)

**Comment by LXGaming** [comment]
You can safely leave that patch disabled, The purpose of it was to remove the stacktrace log spam the mod generated, it looks like they changed the method name which causes the patch to fail.

**Comment by Krutoy242** [comment]
How i can find, if i even have log spam at first place?

And, what dev you talking about?

**Comment by LXGaming** [comment]
That patch was created 3 years ago, chances are that the log spam issue doesn't occur anymore.

The mod in question is EnderIO.

**Comment by Krutoy242** [comment]
I have also this lines in log. Probably this patch actually doesn't make sense.

![image](https://github.com/LXGaming/Sledgehammer/assets/936618/4d3ea5c6-2743-400e-bf8c-9716cba36548)

Thanks for answer!
