### ISSUE TITLE
[Suggestion] MrCrayfish's Furniture Mod fixes

### ISSUE THREAD

**Issue by xJon** [LXGaming/Sledgehammer#46]
Fixing https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/647 would be great.
Improving https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/721 is another suggestion that drastically affects worlds.
Also https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/770 is reported often.
Edit: This is another reported bug - https://github.com/xJon/The-1.12.2-Pack/issues/932.

**Comment by ACGaming** [comment]
Issues will be tackled as part of https://github.com/ACGaming/MrCrayfishFurnitureModLegacy
