### ISSUE TITLE
PlayerChunkMap fix crash on dedicated server

### ISSUE THREAD

**Issue by xJon** [LXGaming/Sledgehammer#48]
https://mclo.gs/UoVqWxk

**Comment by TheComputerizer** [comment]
I just ran into this myself and it seems like it's [this line](https://github.com/LXGaming/Sledgehammer/blob/b37ece811b5cb298ae7e00f27aacd526ca634b4b/src/main/java/io/github/lxgaming/sledgehammer/mixin/core/server/management/PlayerChunkMapMixin.java#L77C79-L77C79) which is probably conflicting with something transforming the PrettyPrinter class from spongeforge. I think setting `player-chunk-map` to false in the core section of the config should fix it

**Comment by xJon** [comment]
> I just ran into this myself and it seems like it's [this line](https://github.com/LXGaming/Sledgehammer/blob/b37ece811b5cb298ae7e00f27aacd526ca634b4b/src/main/java/io/github/lxgaming/sledgehammer/mixin/core/server/management/PlayerChunkMapMixin.java#L77C79-L77C79) which is probably conflicting with something transforming the PrettyPrinter class from spongeforge. I think setting `player-chunk-map` to false in the core section of the config should fix it

Indeed I have disabled `player-chunk-map` in the config after running into this.

**Comment by LXGaming** [comment]
Fixed in [v1.12.2-2.0.25](https://github.com/LXGaming/Sledgehammer/releases/tag/v1.12.2-2.0.25)
