### ISSUE TITLE
ConcurrentModificationException crash with prevent ConcurrentModificationException enabled

### ISSUE THREAD

**Issue by kristi71111** [LXGaming/Sledgehammer#5]
[Crash report](https://pastebin.com/C11pVQxH)
I have "# Prevent ConcurrentModificationException in PlayerChunkMap" set to true in sledgehammer's config file.  Adding any information that might be of use.
CofhWorld version: CoFHWorld-1.12.2-1.3.1.7-universal
SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3843
Forge version: 14.23.5.2838
If you require any more info let me know.

**Comment by LXGaming** [comment]
I don't see Sledgehammer listed in the mods section of that crash report. Can you provide the debug.log file (Zip if it's too large).

**Comment by kristi71111** [comment]
Closing since fixed.
