### ISSUE TITLE
An ERROR occurred on the sponge

### ISSUE THREAD

**Issue by zsn741656478** [LXGaming/Sledgehammer#6]
https://i.loli.net/2019/08/19/mV4PKlTdujUX7xk.png
Running on the Sponge-7.1.7-RC3899
Can fix it?

**Comment by LXGaming** [comment]
The error is intentional, it's added by the `player-chunk-map` fix, You can disable the fix by setting it to false in the config.

**Comment by zsn741656478** [comment]
Oh. I know what the problem is! Sledgehammer and Mirage will conflict.

**Comment by zsn741656478** [comment]
`[12:06:46] [Server thread/WARN] [mixin]: Method overwrite conflict for accessor$getPlayers in mixins.common.core.json:server.management.PlayerchunkMapEntryAccessor, previously written by org.spongepowered.common.mixin.core.server.management.PlayerChunkMapEntryMixin. Skipping method.`
I want to ask by the way, what does this mean?

**Comment by LXGaming** [comment]
No clue but similar warnings show up on a clean server install so you can probably ignore it

**Comment by zsn741656478** [comment]
Will Sledgehammer try to fix the ic2 explosion in the future?
In Sponge, the player's claim cannot be protected when it encounters an ic2 explosion.

**Comment by xElementzx** [comment]
@zsn741656478 sounds like you should report this to the GP dev/GD dev
