### ISSUE TITLE
[1.12.2] Creative search bar issue(?) with FoamFix/Jei/CraftTweaker

### ISSUE THREAD

**Issue by pimalel233** [LXGaming/Sledgehammer#9]
Hello,
little issue for client-side. I think this time I got it right.

Forge 14.23.5.2838
Just Enough Items 4.15.0.293 (to use JEI)
FoamFix 0.10.10 (to use JEI search function in creative search)
Sledgehammer 1.6.6
CraftTweaker 4.1.20

Without sledgehammer or crafttweaker: http://prntscr.com/qw9x8a
(Also tried on my 200 mods modpack, removing sledgehammer fixes the issue: http://prntscr.com/qw9xkl)
5 mentioned mods only (logs attached from running this instance): http://prntscr.com/qw9xog
Once I remove CraftTweaker or Sledgehammer from the instance, filter starts to working again in creative tab.

Logs:
[debug.log](https://github.com/LXGaming/Sledgehammer/files/4143488/debug.log)

Also my configs of mods just in case:
[configs.zip](https://github.com/LXGaming/Sledgehammer/files/4143491/configs.zip) Tried with default sledgehammer config, same thing happens. CT has no additional scripts loaded.

**Comment by LXGaming** [comment]
Try setting `nuke-search-tree` to `false` in the `sledgehammer.conf`.

CraftTweaker attempts to reload the vanilla search tree during client connection, as this is a CPU heavy task in certain modpacks this can cause players with lower-end CPUs to timeout while connecting to a multiplayer server. The side effect of this is the creative search no longer functions.

**Comment by pimalel233** [comment]
You are totally right, it works, I must have double-failed when I tested it yesterday. My guess is I removed sledgehammer.conf from the wrong mc instance I was testing which caused settings to stay unchanged. Sorry for weak troubleshooting.

Though leaving this setting off is a big shame as it significantly reduces time to close my game instance - it basically exits the game instantly. So either that or working filters in creative search. 

edit: to be clear, the filter works in search that JEI adds itself

**Comment by LXGaming** [comment]
Wouldn't think that would change the closing speed of Minecraft.

How are you closing Minecraft? Are you disconnecting from servers first? Clicking quit in the main menu or the X button on the Window?

**Comment by pimalel233** [comment]
In this case it's the X button of the window SSP in-game. While I am testing things, it is just faster anyway.

**Comment by pimalel233** [comment]
FYI, after some more testing with nuke function on, it seems to be affecting 'normal' search. When searching for 'ring', no prefixes, I could not find Baubles Rings in creative search. Same for umberstone from Erebus when searching for 'umberstone'.
Pictures below are shown with function off when it works, no idea why they would not show otherwise. Seems like it is affecting not only filters.
http://prntscr.com/qz8n9i
http://prntscr.com/qz8nio

**Comment by pimalel233** [comment]
After even more testing, it seems that FoamFix's jeiCreativeSearch option is just not stable. I managed to get 'cut' search results in creative search as opposed to jei search when used with random combination of mods, maybe something is overloading. Always disabling that option fixes it. For example, if looking for 'enchantment book' when that option is on in FoamFix you *might* not get result sin creative search. It depends. Sometimes it works, I add any random mods, it might stop working that way. I even downloaded random mod pack - Rebirth-of-the-Night that has FoamFix and that option enabled. Same result, no enchantment books found in creative search, once option is disabled, it works. And since it should replicate Jei search bar which finds these books I guess something is going wrong in specific enviroment. Maybe it is my Forge version? I do not know. But seems like I will be dropping that FoamFix's feature and using back nuke option for fast game closing. Maybe there is another mod that adds FoamFix's Jei funcionality to creative search that works always.

**Comment by LXGaming** [comment]
https://github.com/LXGaming/Sledgehammer/releases/tag/v2.0.9

**Comment by asiekierka** [comment]
jeiCreativeSearch's reason for existence in FoamFix is the major memory savings (on the order of 100-150MB for a large modpack) gained by not having two separate item search trees.

Issue noted at https://github.com/asiekierka/FoamFix/issues/268 - might get around to it in the future, or maybe someone else will.
